
version: 2

models:
    - name: calendar_date
      description: "A standard calendar table"
      columns:
          - name: date_day
            description: "The date"
            tests:
                - unique
                - not_null
    - name: calendar_time
      description: "A standard time table"
      columns:
          - name: time_of_day
            description: "The time of the day"
            tests:
                - unique
                - not_null