
version: 2

models:
    - name: calendar_date
      description: "A starter dbt model"
      columns:
          - name: date_day
            description: "The date"
            tests:
                - unique
                - not_null
    - name: calendar_time
      description: "A starter dbt model"
      columns:
          - name: time_of_day
            description: "The date"
            tests:
                - unique
                - not_null